grafana:
  enabled: true

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.brister.lan

  persistence:
    enabled: true
    storageClassName: microk8s-hostpath
    size: 5Gi

prometheus:
  enabled: true

  prometheusSpec:
    retention: 7d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: microk8s-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: microk8s-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi