apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-test
  namespace: default
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore

  target:
    name: openbao-test
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: homelab/test
        property: username

    - secretKey: password
      remoteRef:
        key: homelab/test
        property: password
