server:
  standalone:
    enabled: false

  ha:
    enabled: true
    replicas: 1

    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = true

        listener "tcp" {
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable     = 1
        }

        storage "raft" {
          path    = "/openbao/data/raft"
          node_id = "openbao-0"
        }

        cluster_addr = "https://openbao-0.openbao-internal:8201"

        seal "static" {
          current_key_id = "homelab-1"
          current_key    = "file:///openbao/secrets/unseal.key"
        }

  dataStorage:
    enabled: true
    storageClass: microk8s-hostpath
    size: 10Gi

  volumes:
    - name: openbao-unseal
      secret:
        secretName: openbao-unseal
        defaultMode: 0400

  volumeMounts:
    - name: openbao-unseal
      mountPath: /openbao/secrets
      readOnly: true

  readinessProbe:
    enabled: true
    path: /v1/sys/health?uninitcode=204&sealedcode=204

ui:
  enabled: true

injector:
  enabled: false
