apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/michaelbrister/homelab-gitops.git
    targetRevision: main
    path: argocd/applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
