ingress:
  enabled: true
  className: traefik

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

  hosts:
    - host: gitea.home.mikebrister.com
      paths:
        - path: /
          pathType: Prefix

service:
  http:
    type: ClusterIP
    port: 3000

persistence:
  enabled: true
  storageClass: microk8s-hostpath
  size: 10Gi

gitea:
  config:
    repository:
      ENABLE_PUSH_CREATE_USER: true
    server:
      DOMAIN: gitea.home.mikebrister.com
      ROOT_URL: https://gitea.home.mikebrister.com/
      PROTOCOL: http

    database:
      DB_TYPE: postgres

postgresql:
  enabled: true

  primary:
    persistence:
      enabled: true
      storageClass: microk8s-hostpath
      size: 10Gi

postgresql-ha:
  enabled: false

redis:
  enabled: false

redis-cluster:
  enabled: false
